name: 'Setup Lazarus environment'

description: 'Setup a Lazarus environment adding it to the PATH'

branding:
  icon: 'chevrons-right'
  color: 'blue'

inputs:
  lazarus-version:  # id of input
    description: 'Version of Lazarus'
    required: true
    default: 'dist'
  include-packages:
    description: 'Include packages that the project needs'
    required: false

runs:
  using: 'node16'
  main: 'dist/main/index.js'

